# Experiment configuration file.

seml:
  conda_environment: 'env-quant-rel-310'
  executable: 'run_quantize.py'
  name: 'quantize_tinyllama_07-11'
  output_dir: '/nfs/homedirs/daro/slurm_output/'
  project_root_dir: '/nfs/homedirs/daro/git/quantization-reliability/'

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: 'gpu:1'       # num GPUs
    mem: '128G'          # memory
    cpus-per-task: 2  # num cores
    time: '1-00:00'     # max time, D-HH:MM
    partition: 'gpu_a100' # partition
#    partition: 'gpu_gtx1080' # partition

###### BEGIN PARAMETER CONFIGURATION ######

fixed:
  device: 'cuda'
  clean_cache: True
  save_quantized_model: True
  quantized_model_save_path: "nfs/students/daro/models"
  seed_model: 123
  seed_dataset: 123
  batch_size: 1
  dataset_stride: 1024
  dataset_seq_length: 1024

grid:
  calib_dataset_name:
    type: choice
    options:
      - 'WikiText'
      - 'OpenAssistant'
      # - 'C4'
      # - 'PTB'

  eval_dataset_name:
    type: choice
    options:
      - 'WikiText'
      - 'OpenAssistant'

  calib_dataset_split:
    type: choice
    options:
      - 'validation'
      # - 'test'

  eval_dataset_split:
    type: choice
    options:
      # - 'validation'
      - 'test'

  eval_metrics:
    type: choice
    options:
      - ['perplexity', 'brier_score', 'quantize_runtime', 'model_size']

  model_name:
    type: choice
    options:
      - 'Llama-3-8B'
      # - 'TinyLlama'

  quantize_config:
    type: choice
    options:
      - {
        quantize_method: "NONE",
        num_bits: 16
      }
      - {
        quantize_method: "BNB",
        num_bits: 4
      }
      - {
        quantize_method: "BNB",
        num_bits: 8
      }
      - {
        quantize_method: "AWQ",
        num_bits: 4
      }
      - {
        quantize_method: "HQQ",
        num_bits: 4
      }
      - {
        quantize_method: "HQQ",
        num_bits: 8
      }

# random:
#   samples: 2
#   seed: 12345
#   batch_size:
#     type: uniform
#     min: 1
#     max: 4
