# Experiment configuration file.

seml:
  conda_environment: 'env-quant-rel-310'
  executable: 'run_quantize.py'
  name: 'quantize_tinyllama'
  output_dir: '/nfs/homedirs/daro/slurm_output/'
  project_root_dir: '/nfs/homedirs/daro/git/quantization-reliability/src/'

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: 'gpu:1'       # num GPUs
    mem: '128G'          # memory
    cpus-per-task: 2  # num cores
    time: '1-00:00'     # max time, D-HH:MM
    partition: 'gpu_a100' # partition
#    partition: 'gpu_gtx1080' # partition

###### BEGIN PARAMETER CONFIGURATION ######

fixed:
  device: 'cuda'
  clean_cache: True
  save_quantized_model: True
  seed_model: 123
  seed_dataset: 123
  batch_size: 1
  stride: 512
  eval_metrics:
    - 'perplexity'
    - 'brier_score'
    - 'model_size'
    - 'gpu_utilization'
  calib_dataset_split:
    - 'validation'
  eval_dataset_split:
    - 'test'

grid:
  calib_dataset_name:
    type: choice
    options:
      - 'WikiText'
      - 'OpenAssistant'

  eval_dataset_name:
    type: choice
    options:
      - 'WikiText'
      - 'OpenAssistant'

  quantize_method:
    type: choice
    options:
      - 'BNB'
      - 'AWQ'

  quantize_params:
    type: choice
    options:
      - {
        "num_bits": 8,
        "llm_int8_threshold": 6.0,
        "llm_int8_enable_fp32_cpu_offload": False,
        "llm_int8_has_fp16_weight": False
      }
      - {
        "num_bits": 4,
        "bnb_4bit_compute_dtype": torch.bfloat16,
        "bnb_4bit_quant_type": "fp4",
        "bnb_4bit_use_double_quant": False,
      }

  model_name:
    type: choice
    options:
      - 'Llama-3-8B'

  # weight_name:
  #   type: choice
  #   options:
  #     - 'DEFAULT'

# random:
#   samples: 2
#   seed: 12345
#   batch_size:
#     type: uniform
#     min: 1
#     max: 4
